{
  "Document": {
    "DocumentId": 2076071891,
    "Title": "Catching Exceptions from System.ComponentModel.BackgroundWorker; DispatcherUnhandledException Fails to Fire for Background Threads",
    "DocumentShortName": null,
    "FileName": null,
    "Path": null,
    "CreateDate": "2007-10-02T11:51:34",
    "ModificationDate": "2007-10-02T11:51:34",
    "TemplateId": null,
    "SegmentId": 83,
    "IsRoot": false,
    "IsActive": true,
    "SortOrdinal": null,
    "ClientId": null,
    "Tag": null
  },
  "Content": "The details of this problem is introduced in “Catch DispatcherUnhandledException from other Thread” here:\n\n    http://forums.microsoft.com/msdn/showpost.aspx?postid=1164067&siteid=1\n\nChango V. of Microsoft answers this issue with this pattern:\n\n(i) Make the Dispatcher object of the main thread available to your worker thread. (You could either pass it as a parameter to the thread start method or just use Application.Current.Dispatcher.)\n\n(ii) Use a try-catch-finally in the worker thread. (In general, the catch block should immediately rethrow critical exceptions: OutOfMemoryException, SecurityException, SEHException, maybe also NullReferenceException.)\n\n(iii) The [worker-thread] catch block calls mainDispatcher.Invoke(DispatcherPriority.Send, ExceptionCallback, exception).\n\n(iv) ExceptionCallback() throws the exception object passed to it. This happens on the main thread, so handlers added to Application.DispatcherUnhandledException will be invoked and can “handle” the exception.\n\n(v) If your worker thread resumes execution, the exception was “handled.”\n\nThe following is a worker-thread catch block following this pattern in a WPF application:\n\n    catch ( Exception ex )\n    {\n        Dispatcher d = ClientApplication.Current.Dispatcher;\n        ClientApplication.WorkerThreadExceptionCallback delg =\n            ClientApplication.WorkerThreadException;\n        d.Invoke( DispatcherPriority.Send, delg, ex );\n\n    }\n\nThe main thread defines:\n\n    internal static void\n        WorkerThreadException( Exception WorkerThreadException )\n    {\n        throw WorkerThreadException as Exception;\n    }\n\n    internal delegate void\n        WorkerThreadExceptionCallback( Exception WorkerThreadException );\n",
  "Tag": "kb2076071891"
}