<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/style.css">
    <title>Catching Exceptions from System.ComponentModel.BackgroundWorker; DispatcherUnhandledException Fails to Fire for Background Threads - the funky knowledge base</title>
</head>
<body>
    <h1>the funky knowledge base</h1>
    <h2>personal notes from way, _way_ back and maybe today</h2>

<section class="entry">
    <h3>Catching Exceptions from System.ComponentModel.BackgroundWorker; DispatcherUnhandledException Fails to Fire for Background Threads</h3>

<pre>
<p>The details of this problem is introduced in “Catch DispatcherUnhandledException from other Thread” here:</p>
<pre><code>http://forums.microsoft.com/msdn/showpost.aspx?postid=1164067&amp;siteid=1
</code></pre>
<p>Chango V. of Microsoft answers this issue with this pattern:</p>
<p>(i) Make the Dispatcher object of the main thread available to your worker thread. (You could either pass it as a parameter to the thread start method or just use Application.Current.Dispatcher.)</p>
<p>(ii) Use a try-catch-finally in the worker thread. (In general, the catch block should immediately rethrow critical exceptions: OutOfMemoryException, SecurityException, SEHException, maybe also NullReferenceException.)</p>
<p>(iii) The [worker-thread] catch block calls mainDispatcher.Invoke(DispatcherPriority.Send, ExceptionCallback, exception).</p>
<p>(iv) ExceptionCallback() throws the exception object passed to it. This happens on the main thread, so handlers added to Application.DispatcherUnhandledException will be invoked and can “handle” the exception.</p>
<p>(v) If your worker thread resumes execution, the exception was “handled.”</p>
<p>The following is a worker-thread catch block following this pattern in a WPF application:</p>
<pre><code>catch ( Exception ex )
{
    Dispatcher d = ClientApplication.Current.Dispatcher;
    ClientApplication.WorkerThreadExceptionCallback delg =
        ClientApplication.WorkerThreadException;
    d.Invoke( DispatcherPriority.Send, delg, ex );

}
</code></pre>
<p>The main thread defines:</p>
<pre><code>internal static void
    WorkerThreadException( Exception WorkerThreadException )
{
    throw WorkerThreadException as Exception;
}

internal delegate void
    WorkerThreadExceptionCallback( Exception WorkerThreadException );
</code></pre>

</pre>

    <span class="date"> <strong>mod date:</strong> 10/2/2007 11:51:34 AM </span>
</section>


<footer>
        &copy; 2019 Bryan D. Wilhite
        <a href="https://twitter.com/BryanWilhite">@BryanWilhite</a>
</footer>
</body>
</html>